// Barème XP par action (cahier section 7.2)

export const XP = {
  SEANCE_MUSCU: 100,
  SEANCE_ZERO_FIRST: 80,
  COURSE: 100,
  RECORD_PERSO: 150,
  REPOS_RESPECTE: 30,
  RAPPEL_RESPECTE: 5,
  MENSURATIONS: 50,
  NUTRITION_QUOTIDIENNE: 20,
  BONUS_SEMAINE: 150,
  ONBOARDING_MENSURATIONS: 50,
  ONBOARDING_RAPPELS: 30,
  ONBOARDING_NUTRITION: 30,
  ONBOARDING_PLANNING: 20,
  MALUS_SEANCE_MANQUEE: -50,
  MALUS_REPOS_NON_RESPECTE: -20,
  MALUS_NUTRITION_NON_ATTEINTE: -10,
} as const;
