export const strings = {
  common: {
    appName: '',
    next: 'Suivant',
    back: 'Retour',
    save: 'Enregistrer',
    cancel: 'Annuler',
    confirm: 'Confirmer',
    delete: 'Supprimer',
    edit: 'Modifier',
    close: 'Fermer',
    yes: 'Oui',
    no: 'Non',
    loading: 'Chargement…',
    error: 'Une erreur est survenue',
    retry: 'Réessayer',
    start: 'Démarrer',
    finish: 'Terminer',
    skip: 'Passer',
    reps: 'reps',
    seconds: 'sec',
    kg: 'kg',
    set: 'Série',
    sets: 'Séries',
  },
  placeholder: {
    title: 'Socle prêt',
    subtitle: 'En attente du Lot 1 — onboarding, Séance Zéro et écran de séance.',
    cta: 'Ouvrir les notes de version',
  },
  onboarding: {
    stepPrenom: {
      title: "Comment tu t'appelles ?",
      subtitle: 'Ton prénom apparaîtra dans tes messages personnalisés.',
      placeholder: 'Entre ton prénom',
      errorRequired: 'Ton prénom est requis',
    },
    stepObjectif: {
      title: 'Quel est ton objectif ?',
      subtitle: 'On sélectionnera le programme le plus adapté.',
      options: {
        recomposition: {
          label: 'Recomposition',
          description: 'Perdre du gras et gagner du muscle simultanément',
        },
        prise_de_masse: {
          label: 'Prise de masse',
          description: 'Développer ta masse musculaire',
        },
        perte: {
          label: 'Perte de poids',
          description: 'Affiner ta silhouette et perdre du gras',
        },
        endurance: {
          label: 'Endurance',
          description: 'Améliorer ta résistance cardiovasculaire',
        },
      },
    },
    stepNiveau: {
      title: 'Quel est ton niveau ?',
      subtitle: "Sois honnête, c'est pour ton bien.",
      options: {
        debutant: {
          label: 'Débutant',
          description: "Je commence ou je reprends l'entraînement",
        },
        intermediaire: {
          label: 'Intermédiaire',
          description: "J'ai 6+ mois d'entraînement régulier",
        },
        confirme: {
          label: 'Confirmé',
          description: 'Plusieurs années de pratique régulière',
        },
      },
    },
    done: {
      title: "C'est parti, {prenom} !",
      subtitle:
        'Ton programme est prêt. Lance ta première séance maintenant — 20 minutes, pas de matériel.',
      ctaSeanceZero: 'Démarrer la Séance Zéro',
      ctaSkip: 'Voir mes programmes',
    },
  },
  home: {
    greeting: 'Bonjour, {prenom}',
    greetingEvening: 'Bonsoir, {prenom}',
    nextSession: 'Prochaine séance',
    noSession: "Repos aujourd'hui",
    resumeBanner: 'Séance en cours',
    resumeAction: 'Reprendre',
    abandonAction: 'Abandonner',
    programs: 'Mes programmes',
    seanceZeroLabel: 'Séance Zéro',
    seanceZeroSubtitle: 'Sans matériel · ~20 min',
    startSeance: 'Démarrer',
  },
  workout: {
    title: 'En séance',
    exercise: 'Exercice',
    serieLabel: 'Série {current}/{total}',
    targetReps: '{min}-{max} reps',
    targetSec: '{min}-{max} sec',
    chargeLabel: 'Charge (kg)',
    repsLabel: 'Répétitions',
    durationLabel: 'Durée (sec)',
    difficulte: {
      label: 'Ressenti',
      facile: 'Facile',
      correct: 'Correct',
      difficile: 'Difficile',
    },
    validateSerie: 'Valider la série',
    nextExercise: 'Exercice suivant',
    finishWorkout: 'Terminer la séance',
    allSeriesDone: 'Toutes les séries sont complétées',
    abandonConfirmTitle: 'Abandonner la séance ?',
    abandonConfirmBody: 'La séance sera enregistrée avec les séries déjà effectuées.',
    abandonConfirmYes: 'Abandonner',
    abandonConfirmNo: 'Continuer',
  },
  summary: {
    title: 'Séance terminée !',
    titleSeanceZero: 'Première séance dans la boîte !',
    xpEarned: '+{xp} XP',
    seriesCompleted: '{n} série{s} complétée{s}',
    backToHome: "Retour à l'accueil",
    nudgeSeanceZero: "Continue comme ça — tes prochaines séances t'attendent sur l'accueil.",
  },
  tabs: {
    home: 'Accueil',
    settings: 'Réglages',
  },
  restTimer: {
    label: 'REPOS',
    skip: 'Passer',
    continue: 'Continuer →',
    done: 'Repos terminé',
    nextSerie: 'Série {current}/{total}',
    nextExercice: 'Prochain : {nom}',
  },
  reorder: {
    button: 'Réorganiser',
    title: 'Réorganiser les exercices',
    done: 'Terminé',
    hint: 'Déplacez les exercices restants avec les flèches.',
  },
  history: {
    title: 'Progression',
    noData: 'Aucune donnée pour cet exercice.\nComplétez une séance pour voir votre progression.',
    sessions: 'Séances passées',
    chartLabelCharge: 'Charge maximale',
    chartLabelReps: 'Répétitions maximales',
    serieCount: '{n} série{s}',
    totalReps: '{n} reps total',
  },
  progressionSuggestions: {
    title: 'Progression suggérée 🚀',
    charge: '+2,5 kg → vise {suggested} kg sur {nom}',
    reps: '+2 reps → vise {suggested} reps sur {nom}',
    variante: 'Essaie une variante plus difficile sur {nom} : {variante}',
  },
  programs: {
    title: 'Mes programmes',
    editButton: 'Modifier',
    editScreenTitle: 'Modifier le programme',
    addExercice: '+ Ajouter un exercice',
    removeExercice: 'Retirer',
    removeConfirmTitle: 'Retirer {nom} du programme ?',
    removeConfirmBody: 'Les données passées (historique) ne sont pas supprimées.',
    seriesRepsLabel: '{series} séries · {min}–{max} reps',
    editConfigTitle: 'Modifier la configuration',
    seriesLabel: 'Séries',
    repsMinLabel: 'Reps min',
    repsMaxLabel: 'Reps max',
    noExercices: 'Aucun exercice dans ce programme.',
    exercicePickerTitle: 'Ajouter un exercice',
    exercicePickerSubtitle: 'Sélectionnez un exercice du catalogue.',
    defaultSeries: '3',
    defaultRepsMin: '8',
    defaultRepsMax: '12',
    configSectionTitle: 'Configuration',
    addToProgram: 'Ajouter au programme',
    viewHistory: 'Progression',
  },
  settings: {
    title: 'Réglages',
    programs: 'Programmes',
    programsSubtitle: 'Modifier vos séances types',
    profile: 'Profil',
    profileName: 'Prénom',
    dangerZone: 'Zone danger',
    version: 'Version {v}',
  },
} as const;

export type Strings = typeof strings;
