export const strings = {
  common: {
    appName: '',
    next: 'Suivant',
    back: 'Retour',
    save: 'Enregistrer',
    cancel: 'Annuler',
    confirm: 'Confirmer',
    ok: 'OK',
    delete: 'Supprimer',
    edit: 'Modifier',
    close: 'Fermer',
    yes: 'Oui',
    no: 'Non',
    loading: 'Chargement…',
    error: 'Une erreur est survenue',
    retry: 'Réessayer',
    start: 'Démarrer',
    finish: 'Terminer',
    skip: 'Passer',
    reps: 'reps',
    seconds: 'sec',
    kg: 'kg',
    set: 'Série',
    sets: 'Séries',
  },
  placeholder: {
    title: 'Socle prêt',
    subtitle: 'En attente du Lot 1 — onboarding, Séance Zéro et écran de séance.',
    cta: 'Ouvrir les notes de version',
  },
  onboarding: {
    stepPrenom: {
      title: "Comment tu t'appelles ?",
      subtitle: 'Ton prénom apparaîtra dans tes messages personnalisés.',
      placeholder: 'Entre ton prénom',
      errorRequired: 'Ton prénom est requis',
    },
    stepObjectif: {
      title: 'Quel est ton objectif ?',
      subtitle: 'On sélectionnera le programme le plus adapté.',
      options: {
        recomposition: {
          label: 'Recomposition',
          description: 'Perdre du gras et gagner du muscle simultanément',
        },
        prise_de_masse: {
          label: 'Prise de masse',
          description: 'Développer ta masse musculaire',
        },
        perte: {
          label: 'Perte de poids',
          description: 'Affiner ta silhouette et perdre du gras',
        },
        endurance: {
          label: 'Endurance',
          description: 'Améliorer ta résistance cardiovasculaire',
        },
      },
    },
    stepNiveau: {
      title: 'Quel est ton niveau ?',
      subtitle: "Sois honnête, c'est pour ton bien.",
      options: {
        debutant: {
          label: 'Débutant',
          description: "Je commence ou je reprends l'entraînement",
        },
        intermediaire: {
          label: 'Intermédiaire',
          description: "J'ai 6+ mois d'entraînement régulier",
        },
        confirme: {
          label: 'Confirmé',
          description: 'Plusieurs années de pratique régulière',
        },
      },
    },
    done: {
      title: "C'est parti, {prenom} !",
      subtitle:
        'Ton programme est prêt. Lance ta première séance maintenant — 20 minutes, pas de matériel.',
      ctaSeanceZero: 'Démarrer la Séance Zéro',
      ctaSkip: 'Voir mes programmes',
    },
  },
  home: {
    greeting: 'Bonjour, {prenom}',
    greetingEvening: 'Bonsoir, {prenom}',
    nextSession: 'Prochaine séance',
    noSession: "Repos aujourd'hui",
    resumeBanner: 'Séance en cours',
    resumeAction: 'Reprendre',
    abandonAction: 'Abandonner',
    programs: 'Mes programmes',
    seanceZeroLabel: 'Séance Zéro',
    seanceZeroSubtitle: 'Sans matériel · ~20 min',
    startSeance: 'Démarrer',
  },
  workout: {
    title: 'En séance',
    exercise: 'Exercice',
    serieLabel: 'Série {current}/{total}',
    targetReps: '{min}-{max} reps',
    targetSec: '{min}-{max} sec',
    chargeLabel: 'Charge (kg)',
    repsLabel: 'Répétitions',
    durationLabel: 'Durée (sec)',
    difficulte: {
      label: 'Ressenti',
      facile: 'Facile',
      correct: 'Correct',
      difficile: 'Difficile',
    },
    validateSerie: 'Valider la série',
    nextExercise: 'Exercice suivant',
    finishWorkout: 'Terminer la séance',
    allSeriesDone: 'Toutes les séries sont complétées',
    abandonConfirmTitle: 'Abandonner la séance ?',
    abandonConfirmBody: 'La séance sera enregistrée avec les séries déjà effectuées.',
    abandonConfirmYes: 'Abandonner',
    abandonConfirmNo: 'Continuer',
  },
  summary: {
    title: 'Séance terminée !',
    titleSeanceZero: 'Première séance dans la boîte !',
    xpEarned: '+{xp} XP',
    xpEarnedLabel: 'XP gagné',
    xpBonusFirstTime: 'Bonus première fois !',
    seriesCompleted: '{n} série{s} complétée{s}',
    backToHome: "Retour à l'accueil",
    nudgeSeanceZero: "Continue comme ça — tes prochaines séances t'attendent sur l'accueil.",
  },
  tabs: {
    home: 'Accueil',
    settings: 'Réglages',
  },
  restTimer: {
    label: 'REPOS',
    skip: 'Passer',
    continue: 'Continuer →',
    done: 'Repos terminé',
    nextSerie: 'Série {current}/{total}',
    nextExercice: 'Prochain : {nom}',
  },
  reorder: {
    button: 'Réorganiser',
    title: 'Réorganiser les exercices',
    done: 'Terminé',
    hint: 'Déplacez les exercices restants avec les flèches.',
  },
  history: {
    title: 'Progression',
    noData: 'Aucune donnée pour cet exercice.\nComplétez une séance pour voir votre progression.',
    sessions: 'Séances passées',
    chartLabelCharge: 'Charge maximale',
    chartLabelReps: 'Répétitions maximales',
    serieCount: '{n} série{s}',
    totalReps: '{n} reps total',
  },
  progressionSuggestions: {
    title: 'Progression suggérée 🚀',
    charge: '+2,5 kg → vise {suggested} kg sur {nom}',
    reps: '+2 reps → vise {suggested} reps sur {nom}',
    variante: 'Essaie une variante plus difficile sur {nom} : {variante}',
  },
  programs: {
    title: 'Mes programmes',
    editButton: 'Modifier',
    editScreenTitle: 'Modifier le programme',
    addExercice: '+ Ajouter un exercice',
    removeExercice: 'Retirer',
    removeConfirmTitle: 'Retirer {nom} du programme ?',
    removeConfirmBody: 'Les données passées (historique) ne sont pas supprimées.',
    seriesRepsLabel: '{series} séries · {min}–{max} reps',
    editConfigTitle: 'Modifier la configuration',
    seriesLabel: 'Séries',
    repsMinLabel: 'Reps min',
    repsMaxLabel: 'Reps max',
    noExercices: 'Aucun exercice dans ce programme.',
    exercicePickerTitle: 'Ajouter un exercice',
    exercicePickerSubtitle: 'Sélectionnez un exercice du catalogue.',
    defaultSeries: '3',
    defaultRepsMin: '8',
    defaultRepsMax: '12',
    configSectionTitle: 'Configuration',
    addToProgram: 'Ajouter au programme',
    viewHistory: 'Progression',
  },
  settings: {
    title: 'Réglages',
    entrainement: 'Entraînement',
    programs: 'Programmes',
    programsSubtitle: 'Modifier vos séances types',
    planning: 'Planning',
    planningSubtitle: "Organise ta semaine d'entraînement",
    reminders: 'Rappels',
    remindersSubtitle: 'Notifications de routine',
    nutrition: 'Nutrition',
    nutritionSubtitle: 'Objectifs calories et protéines',
    profile: 'Profil',
    profileName: 'Prénom',
    donneesSection: 'Données',
    exportLabel: 'Exporter la sauvegarde',
    exportSubtitle: 'Partage un fichier JSON avec toutes tes données',
    exportSuccess: 'Sauvegarde partagée avec succès.',
    exportError: 'Impossible de partager la sauvegarde.',
    importLabel: 'Importer une sauvegarde',
    importSubtitle: 'Restaure depuis un fichier JSON',
    importSuccess: "Données importées avec succès. Relance l'application pour tout voir.",
    importErrorInvalid: 'Fichier invalide ou corrompu.',
    importErrorVersion: 'Version de sauvegarde incompatible.',
    importErrorGeneric: "Erreur lors de l'import.",
    importConfirmTitle: 'Importer cette sauvegarde ?',
    importConfirmBody:
      'Toutes tes données actuelles seront remplacées par celles de la sauvegarde. Cette action est irréversible.',
    importConfirmYes: 'Importer',
    dangerZone: 'Zone danger',
    clearLabel: 'Effacer toutes mes données',
    clearSubtitle: "Remet l'application dans son état initial",
    clearConfirm1Title: 'Effacer toutes les données ?',
    clearConfirm1Body:
      'Cette action supprimera définitivement tous tes entraînements, mesures, courses et paramètres. Elle est irréversible.',
    clearConfirm1Yes: 'Continuer',
    clearConfirm2Title: 'Dernière confirmation',
    clearConfirm2Body:
      'Toutes tes données seront perdues. Es-tu vraiment sûr de vouloir tout effacer ?',
    clearConfirm2Yes: 'Tout effacer',
    clearSuccess: "Données effacées. L'application va redémarrer.",
    clearError: "Erreur lors de l'effacement.",
    version: 'Version {v}',
    aboutSection: 'À propos',
    checkUpdateLabel: 'Mises à jour',
    checkUpdateSubtitle: 'Vérifier si une version plus récente existe',
    checkUpdateButton: 'Vérifier',
    checkUpToDate: 'Tu es à jour ✓',
    checkAvailable: 'Version {v} disponible !',
    checkError: 'Vérification impossible. Réessaie plus tard.',
  },
  updates: {
    bannerTitle: 'Mise à jour disponible',
    bannerSubtitle: 'Version {v} · appuie pour voir les nouveautés',
    bannerAction: 'Mettre à jour',
    dismissA11y: 'Masquer la bannière de mise à jour',
    notesTitle: 'Nouvelle version',
    notesVersionLabel: 'Version {v}',
    notesEmpty: 'Aucune note de version fournie pour cette mise à jour.',
    notesViewOnline: 'Voir sur GitHub',
    installAndroid: "Télécharger l'APK",
    installIos: 'Ouvrir TestFlight',
    updateGeneric: 'Mettre à jour',
  },
  nutrition: {
    setupTitle: 'Objectifs nutritionnels',
    setupSubtitle: 'Définis tes cibles de calories et de protéines.',
    kcalLabel: 'Calories cibles',
    proteinesLabel: 'Protéines cibles',
    errorInvalid: 'Saisis des valeurs valides supérieures à 0.',
    todayTitle: 'Nutrition du jour',
    validateLabel: "Objectifs atteints aujourd'hui ?",
    validated: 'Objectifs atteints ✓',
    notValidated: 'Non validé',
    validate: 'Valider',
    unvalidate: 'Annuler',
    kcalUnit: 'kcal/j',
    proteinesUnit: 'g protéines/j',
    configureLabel: 'Configurer mes objectifs',
  },
  gamification: {
    streakLabel: 'Streak',
    streakDays: '{n} jour{s}',
    xpLabel: 'XP',
    rankLabel: 'Rang',
    nextRank: 'Prochain rang',
    gagne_tes_xp: '⚡ Gagne tes premiers XP',
    progression: '{done}/{total} complété{s}',
    modules: {
      mensurations: {
        label: '📸 Mensurations de départ',
        accroche: 'Vois ta transformation semaine après semaine',
        xp: '+50 XP',
      },
      rappels: {
        label: '🔔 Rappels personnalisés',
        accroche: 'Ne rate plus jamais une séance',
        xp: '+30 XP',
      },
      nutrition: {
        label: '🍽️ Objectifs nutritionnels',
        accroche: 'Cible tes calories et protéines quotidiennes',
        xp: '+30 XP',
      },
      planning: {
        label: '📅 Planning hebdomadaire',
        accroche: "Organise ta semaine d'entraînement",
        xp: '+20 XP',
      },
    },
  },
  reminders: {
    title: 'Rappels',
    subtitle: 'Active et configure tes notifications de routine.',
    editTime: 'Modifier',
    invalidTime: "Format invalide. Saisis l'heure au format HH:MM (ex: 06:45).",
    types: {
      seance_musculation: 'Séance de musculation',
      course: 'Course à pied',
      hydratation: 'Hydratation',
      petit_dejeuner: 'Petit-déjeuner',
      dejeuner: 'Déjeuner',
      collation: 'Collation',
      diner: 'Dîner',
      pause_posture: 'Pause posture',
      mensurations: 'Mensurations',
    },
    desc_seance_musculation: 'Jours de musculation uniquement (selon ton planning).',
    desc_course: 'Jours de course uniquement (selon ton planning).',
    desc_hydratation: 'Toutes les 2h de 9h à 19h.',
    desc_petit_dejeuner: 'Rappel quotidien.',
    desc_dejeuner: 'Rappel quotidien.',
    desc_collation: 'Rappel quotidien.',
    desc_diner: 'Rappel quotidien.',
    desc_pause_posture: 'Toutes les heures de 9h à 18h.',
    desc_mensurations: 'Chaque samedi.',
  },
  bodyTracking: {
    tabLabel: 'Corps',
    title: 'Suivi corporel',
    addMeasure: 'Ajouter une mesure',
    noMeasures: 'Aucune mesure enregistrée.\nAjoute ta première mesure pour suivre ta progression.',
    lastMeasure: 'Dernière mesure',
    chartSection: 'Évolution',
    photosSection: 'Photos de progression',
    noPhotos: 'Aucune photo enregistrée.',
    measures: {
      poids_kg: 'Poids',
      tour_taille_cm: 'Tour de taille',
      tour_hanches_cm: 'Tour des hanches',
      tour_poitrine_cm: 'Tour de poitrine',
      tour_bras_cm: 'Tour de bras',
      tour_cuisses_cm: 'Tour des cuisses',
    },
    units: {
      poids_kg: 'kg',
      tour_taille_cm: 'cm',
      tour_hanches_cm: 'cm',
      tour_poitrine_cm: 'cm',
      tour_bras_cm: 'cm',
      tour_cuisses_cm: 'cm',
    },
    deleteConfirmTitle: 'Supprimer cette mesure ?',
    deleteConfirmBody: 'Cette action est irréversible.',
  },
  running: {
    tabLabel: 'Course',
    title: 'Course à pied',
    addRun: 'Enregistrer une sortie',
    noRuns: 'Aucune sortie enregistrée.\nEnregistre ta première sortie pour suivre ta progression.',
    statsSection: 'Statistiques',
    volumeHebdo: 'Cette semaine',
    volumeMensuel: 'Ce mois',
    recordsSection: 'Records personnels',
    recordDistance: 'Distance max',
    recordAllure: 'Meilleure allure',
    chartSection: "Progression de l'allure",
    historySection: 'Historique',
    newRecord: 'Nouveau record ! 🏆',
    newRecordDistance: 'Nouvelle distance record : {dist} km',
    newRecordAllure: 'Nouvelle allure record : {allure}',
    deleteConfirmTitle: 'Supprimer cette sortie ?',
    deleteConfirmBody: 'Cette action est irréversible.',
    ressenti: {
      label: 'Ressenti',
      '1': 'Très facile',
      '2': 'Facile',
      '3': 'Modéré',
      '4': 'Difficile',
      '5': 'Épuisant',
    },
    km: 'km',
    min: 'min',
    sec: 'sec',
    distanceLabel: 'Distance (km)',
    minutesLabel: 'Durée — minutes',
    secondsLabel: 'Durée — secondes',
    notesLabel: 'Notes (optionnel)',
    errorNoDistance: 'Saisis une distance valide.',
    errorNoDuration: 'Saisis une durée valide.',
    allurePreview: 'Allure : {allure}',
  },
  planning: {
    title: 'Planning hebdomadaire',
    subtitle: 'Configure ton programme semaine par semaine.',
    settingsLabel: 'Planning',
    settingsSubtitle: "Organise ta semaine d'entraînement",
    days: {
      lundi: 'Lundi',
      mardi: 'Mardi',
      mercredi: 'Mercredi',
      jeudi: 'Jeudi',
      vendredi: 'Vendredi',
      samedi: 'Samedi',
      dimanche: 'Dimanche',
    },
    activites: {
      musculation_haut: 'Haut du corps',
      musculation_bas: 'Bas du corps',
      course: 'Course',
      repos: 'Repos',
    },
    savedSuccess: 'Planning enregistré !',
    todayActivity: 'Activité du jour',
    todayRest: 'Jour de repos',
    todayRestMsg: 'Profite de ta récupération.',
    todayRunMsg: "Une sortie est prévue aujourd'hui.",
    todayMuscuMsg: "Une séance est prévue aujourd'hui.",
  },
  addMeasure: {
    title: 'Nouvelle mesure',
    editTitle: 'Modifier la mesure',
    dateLabel: 'Date',
    poidsLabel: 'Poids (kg)',
    tailleLabe: 'Tour de taille (cm)',
    hanchesLabel: 'Tour des hanches (cm)',
    poitrineLabel: 'Tour de poitrine (cm)',
    brasLabel: 'Tour de bras (cm)',
    cuissesLabel: 'Tour des cuisses (cm)',
    notesLabel: 'Notes (optionnel)',
    photoLabel: 'Photo de progression',
    addPhoto: 'Ajouter une photo',
    changePhoto: 'Changer la photo',
    removePhoto: 'Supprimer la photo',
    photoSourceTitle: 'Ajouter une photo',
    photoSourceCamera: 'Prendre une photo',
    photoSourceGallery: 'Choisir depuis la galerie',
    errorEmpty: 'Saisis au moins une valeur.',
    savedSuccess: 'Mesure enregistrée !',
    permissionDeniedTitle: 'Permission refusée',
    permissionGallery: "L'accès à la galerie est nécessaire.",
    permissionCamera: "L'accès à la caméra est nécessaire.",
  },
} as const;

export type Strings = typeof strings;
